---
- hosts: all
  become: yes
  vars_files:
   - config.yaml
  vars:
   new_user: "{{ user_name }}"
  tasks:
  - name: Install python3 and pip3
    package:
      name: 
        -"{{ python_package }}"
        -"{{ pip_package }}"
      state: latest
    when : ansible_distribution in ["Debian","ubuntu"]

  - name: Set pip3 as default pip
    command: "ln -sf /usr/bin/pip3 /usr/bin/pip"
    when : ansible_distribution in ["Debian","ubuntu"]

  - name: Set python3 as default python
    command: "ln -sf /usr/bin/python3 /usr/bin/python"
    when : ansible_distribution in ["Debian","ubuntu"]

 
  - name: Install OpenJDK Java
    package:
      name:
        -{{ "java_package" }}
      state: latest
    when : ansible_distribution in ["Debian","ubuntu"]
 
  - name: Create MOTD
    template:
       src: /home/jozette/Fermin_PrelimExam/motd.j2
       dest: etc/motd

  - name: Create user
    user:
      name: "{{ josh }}"
      state: present
      shell: /bin/bash
   
